"""Add status column to User model

Revision ID: 492285771107
Revises: 3a6f438420b8
Create Date: 2024-12-20 06:14:47.218148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492285771107'
down_revision = '3a6f438420b8'
branch_labels = None
depends_on = None


def upgrade():
    # Modify the column definition to include a default value
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_status', sa.String(length=50), nullable=False, server_default='active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_status')

    # ### end Alembic commands ###
